[package]
name = "frobt-wasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "frobtwasm"
crate-type = ["cdylib", "rlib"]

[dependencies]
frobtlib = { path = "../frobt", default-features = false, package = "frobt" }
frost-session = { path = "../frost-session" }
frost-ceremony = { path = "../frost-ceremony" }
wasm-bindgen = "0.2"
frost-core = { version = "2", features = ["internals"] }
frost-secp256k1 = "=2.2.0"
rand = "0.8"
zeroize = "1"
hex = "0.4"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
