[workspace]
resolver = "2"
members = [
    "crates/frost-ffi",
    "crates/frost-ceremony",
    "crates/frozts-lib",
    "crates/frozts-sdk",
    "crates/frozts-wasm",
    "crates/frozto-lib",
    "crates/frozto-wasm",
    "crates/frozto-sdk",
    "crates/fromt-lib",
    "crates/fromt-sdk",
    "crates/fromt-wasm",
    "crates/frost-session",
]

[patch.crates-io]
reddsa = { git = "https://github.com/ZcashFoundation/reddsa.git", rev = "475a552" }
