[workspace]
resolver = "2"
members = [
    "crates/frost-ffi",
    "crates/frost-ceremony",
    "crates/frost-session",
    "crates/frosty",
    "crates/frobt",
    "crates/froeth",
    "crates/fromt",
    "crates/frosst",
    "crates/frobt-wasm",
    "crates/froeth-wasm",
    "crates/fromt-sdk",
    "crates/fromt-wasm",
    "crates/frozt-lib",
    "crates/frozt-sdk",
    "crates/frozt-wasm",
    "crates/test-vectors",
]

[patch.crates-io]
reddsa = { git = "https://github.com/ZcashFoundation/reddsa.git", rev = "475a552" }
