[package]
name = "froeth"
version = "0.1.0"
edition = "2021"

[lib]
name = "froethlib"
crate-type = ["cdylib", "rlib"]

[dependencies]
frosty = { path = "../frosty" }
frost-ffi = { path = "../frost-ffi" }
frost-ceremony = { path = "../frost-ceremony" }
frost-core = { version = "2", features = ["internals"] }
frost-secp256k1 = "=2.2.0"
k256 = { version = "0.13", features = ["arithmetic"] }
rand = "0.8"
hex = "0.4"
sha2 = "0.10"
hmac = "0.12"
tiny-keccak = { version = "2", features = ["keccak"] }
paste = "1"

[dev-dependencies]
frosty = { path = "../frosty", features = ["test-helpers"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
