[package]
name = "fromt-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fromt-lib = { path = "../fromt-lib", default-features = false }
frost-session = { path = "../frost-session" }
frost-ceremony = { path = "../frost-ceremony" }
wasm-bindgen = "0.2"
frost-core = { version = "2", features = ["internals"] }
frost-ed25519 = "2"
curve25519-dalek = { version = "4", features = ["serde"] }
rand = "0.8"
zeroize = "1"
tiny-keccak = { version = "2", features = ["keccak"] }
hex = "0.4"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
monero-wallet = { git = "https://github.com/monero-oxide/monero-oxide", default-features = false, features = ["std", "multisig", "compile-time-generators"] }
modular-frost = { version = "0.11", default-features = false, features = ["ed25519"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
