// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/lightwalletd/compact_formats.proto

package lightwalletd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockID) Reset() {
	*x = BlockID{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockID) ProtoMessage() {}

func (x *BlockID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockID.ProtoReflect.Descriptor instead.
func (*BlockID) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{0}
}

func (x *BlockID) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BlockRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *BlockID               `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *BlockID               `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRange) GetStart() *BlockID {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *BlockRange) GetEnd() *BlockID {
	if x != nil {
		return x.End
	}
	return nil
}

type ChainSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSpec) Reset() {
	*x = ChainSpec{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSpec) ProtoMessage() {}

func (x *ChainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSpec.ProtoReflect.Descriptor instead.
func (*ChainSpec) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{3}
}

type LightdInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Version                 string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Vendor                  string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	TaddrSupport            bool                   `protobuf:"varint,3,opt,name=taddrSupport,proto3" json:"taddrSupport,omitempty"`
	ChainName               string                 `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`
	SaplingActivationHeight uint64                 `protobuf:"varint,5,opt,name=saplingActivationHeight,proto3" json:"saplingActivationHeight,omitempty"`
	ConsensusBranchId       string                 `protobuf:"bytes,6,opt,name=consensusBranchId,proto3" json:"consensusBranchId,omitempty"`
	BlockHeight             uint64                 `protobuf:"varint,7,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	GitCommit               string                 `protobuf:"bytes,8,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	Branch                  string                 `protobuf:"bytes,9,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildDate               string                 `protobuf:"bytes,10,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	BuildUser               string                 `protobuf:"bytes,11,opt,name=buildUser,proto3" json:"buildUser,omitempty"`
	EstimatedHeight         uint64                 `protobuf:"varint,12,opt,name=estimatedHeight,proto3" json:"estimatedHeight,omitempty"`
	ZcashdBuild             string                 `protobuf:"bytes,13,opt,name=zcashdBuild,proto3" json:"zcashdBuild,omitempty"`
	ZcashdSubversion        string                 `protobuf:"bytes,14,opt,name=zcashdSubversion,proto3" json:"zcashdSubversion,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LightdInfo) Reset() {
	*x = LightdInfo{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightdInfo) ProtoMessage() {}

func (x *LightdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightdInfo.ProtoReflect.Descriptor instead.
func (*LightdInfo) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{4}
}

func (x *LightdInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LightdInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *LightdInfo) GetTaddrSupport() bool {
	if x != nil {
		return x.TaddrSupport
	}
	return false
}

func (x *LightdInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *LightdInfo) GetSaplingActivationHeight() uint64 {
	if x != nil {
		return x.SaplingActivationHeight
	}
	return 0
}

func (x *LightdInfo) GetConsensusBranchId() string {
	if x != nil {
		return x.ConsensusBranchId
	}
	return ""
}

func (x *LightdInfo) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *LightdInfo) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *LightdInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *LightdInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *LightdInfo) GetBuildUser() string {
	if x != nil {
		return x.BuildUser
	}
	return ""
}

func (x *LightdInfo) GetEstimatedHeight() uint64 {
	if x != nil {
		return x.EstimatedHeight
	}
	return 0
}

func (x *LightdInfo) GetZcashdBuild() string {
	if x != nil {
		return x.ZcashdBuild
	}
	return ""
}

func (x *LightdInfo) GetZcashdSubversion() string {
	if x != nil {
		return x.ZcashdSubversion
	}
	return ""
}

type CompactBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoVersion  uint32                 `protobuf:"varint,1,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevHash      []byte                 `protobuf:"bytes,4,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Time          uint32                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Header        []byte                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	Vtx           []*CompactTx           `protobuf:"bytes,7,rep,name=vtx,proto3" json:"vtx,omitempty"`
	ChainMetadata *ChainMetadata         `protobuf:"bytes,8,opt,name=chainMetadata,proto3" json:"chainMetadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactBlock) Reset() {
	*x = CompactBlock{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactBlock) ProtoMessage() {}

func (x *CompactBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactBlock.ProtoReflect.Descriptor instead.
func (*CompactBlock) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{5}
}

func (x *CompactBlock) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *CompactBlock) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CompactBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CompactBlock) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *CompactBlock) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CompactBlock) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CompactBlock) GetVtx() []*CompactTx {
	if x != nil {
		return x.Vtx
	}
	return nil
}

func (x *CompactBlock) GetChainMetadata() *ChainMetadata {
	if x != nil {
		return x.ChainMetadata
	}
	return nil
}

type ChainMetadata struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SaplingCommitmentTreeSize uint32                 `protobuf:"varint,1,opt,name=saplingCommitmentTreeSize,proto3" json:"saplingCommitmentTreeSize,omitempty"`
	OrchardCommitmentTreeSize uint32                 `protobuf:"varint,2,opt,name=orchardCommitmentTreeSize,proto3" json:"orchardCommitmentTreeSize,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ChainMetadata) Reset() {
	*x = ChainMetadata{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadata) ProtoMessage() {}

func (x *ChainMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadata.ProtoReflect.Descriptor instead.
func (*ChainMetadata) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{6}
}

func (x *ChainMetadata) GetSaplingCommitmentTreeSize() uint32 {
	if x != nil {
		return x.SaplingCommitmentTreeSize
	}
	return 0
}

func (x *ChainMetadata) GetOrchardCommitmentTreeSize() uint32 {
	if x != nil {
		return x.OrchardCommitmentTreeSize
	}
	return 0
}

type CompactTx struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Index         uint64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash          []byte                  `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Fee           uint32                  `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Spends        []*CompactSaplingSpend  `protobuf:"bytes,4,rep,name=spends,proto3" json:"spends,omitempty"`
	Outputs       []*CompactSaplingOutput `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Actions       []*CompactOrchardAction `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactTx) Reset() {
	*x = CompactTx{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactTx) ProtoMessage() {}

func (x *CompactTx) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactTx.ProtoReflect.Descriptor instead.
func (*CompactTx) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{7}
}

func (x *CompactTx) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CompactTx) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CompactTx) GetFee() uint32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *CompactTx) GetSpends() []*CompactSaplingSpend {
	if x != nil {
		return x.Spends
	}
	return nil
}

func (x *CompactTx) GetOutputs() []*CompactSaplingOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *CompactTx) GetActions() []*CompactOrchardAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type CompactSaplingSpend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nf            []byte                 `protobuf:"bytes,1,opt,name=nf,proto3" json:"nf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactSaplingSpend) Reset() {
	*x = CompactSaplingSpend{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactSaplingSpend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactSaplingSpend) ProtoMessage() {}

func (x *CompactSaplingSpend) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactSaplingSpend.ProtoReflect.Descriptor instead.
func (*CompactSaplingSpend) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{8}
}

func (x *CompactSaplingSpend) GetNf() []byte {
	if x != nil {
		return x.Nf
	}
	return nil
}

type CompactSaplingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmu           []byte                 `protobuf:"bytes,1,opt,name=cmu,proto3" json:"cmu,omitempty"`
	EphemeralKey  []byte                 `protobuf:"bytes,2,opt,name=ephemeralKey,proto3" json:"ephemeralKey,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactSaplingOutput) Reset() {
	*x = CompactSaplingOutput{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactSaplingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactSaplingOutput) ProtoMessage() {}

func (x *CompactSaplingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactSaplingOutput.ProtoReflect.Descriptor instead.
func (*CompactSaplingOutput) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{9}
}

func (x *CompactSaplingOutput) GetCmu() []byte {
	if x != nil {
		return x.Cmu
	}
	return nil
}

func (x *CompactSaplingOutput) GetEphemeralKey() []byte {
	if x != nil {
		return x.EphemeralKey
	}
	return nil
}

func (x *CompactSaplingOutput) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type CompactOrchardAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullifier     []byte                 `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	Cmx           []byte                 `protobuf:"bytes,2,opt,name=cmx,proto3" json:"cmx,omitempty"`
	EphemeralKey  []byte                 `protobuf:"bytes,3,opt,name=ephemeralKey,proto3" json:"ephemeralKey,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactOrchardAction) Reset() {
	*x = CompactOrchardAction{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactOrchardAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactOrchardAction) ProtoMessage() {}

func (x *CompactOrchardAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactOrchardAction.ProtoReflect.Descriptor instead.
func (*CompactOrchardAction) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{10}
}

func (x *CompactOrchardAction) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

func (x *CompactOrchardAction) GetCmx() []byte {
	if x != nil {
		return x.Cmx
	}
	return nil
}

func (x *CompactOrchardAction) GetEphemeralKey() []byte {
	if x != nil {
		return x.EphemeralKey
	}
	return nil
}

func (x *CompactOrchardAction) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type TxFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockID               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxFilter) Reset() {
	*x = TxFilter{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxFilter) ProtoMessage() {}

func (x *TxFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxFilter.ProtoReflect.Descriptor instead.
func (*TxFilter) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{11}
}

func (x *TxFilter) GetBlock() *BlockID {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *TxFilter) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxFilter) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type RawTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTransaction) Reset() {
	*x = RawTransaction{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTransaction) ProtoMessage() {}

func (x *RawTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTransaction.ProtoReflect.Descriptor instead.
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{12}
}

func (x *RawTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawTransaction) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type TreeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Time          uint32                 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	SaplingTree   string                 `protobuf:"bytes,5,opt,name=saplingTree,proto3" json:"saplingTree,omitempty"`
	OrchardTree   string                 `protobuf:"bytes,6,opt,name=orchardTree,proto3" json:"orchardTree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeState) Reset() {
	*x = TreeState{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeState) ProtoMessage() {}

func (x *TreeState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeState.ProtoReflect.Descriptor instead.
func (*TreeState) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{13}
}

func (x *TreeState) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TreeState) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TreeState) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TreeState) GetSaplingTree() string {
	if x != nil {
		return x.SaplingTree
	}
	return ""
}

func (x *TreeState) GetOrchardTree() string {
	if x != nil {
		return x.OrchardTree
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_lightwalletd_compact_formats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_internal_lightwalletd_compact_formats_proto_rawDescGZIP(), []int{14}
}

func (x *SendResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SendResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_internal_lightwalletd_compact_formats_proto protoreflect.FileDescriptor

const file_internal_lightwalletd_compact_formats_proto_rawDesc = "" +
	"\n" +
	"+internal/lightwalletd/compact_formats.proto\x12\x15cash.z.wallet.sdk.rpc\"5\n" +
	"\aBlockID\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"t\n" +
	"\n" +
	"BlockRange\x124\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x05start\x120\n" +
	"\x03end\x18\x02 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x03end\"\v\n" +
	"\tChainSpec\"\a\n" +
	"\x05Empty\"\xf4\x03\n" +
	"\n" +
	"LightdInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\"\n" +
	"\ftaddrSupport\x18\x03 \x01(\bR\ftaddrSupport\x12\x1c\n" +
	"\tchainName\x18\x04 \x01(\tR\tchainName\x128\n" +
	"\x17saplingActivationHeight\x18\x05 \x01(\x04R\x17saplingActivationHeight\x12,\n" +
	"\x11consensusBranchId\x18\x06 \x01(\tR\x11consensusBranchId\x12 \n" +
	"\vblockHeight\x18\a \x01(\x04R\vblockHeight\x12\x1c\n" +
	"\tgitCommit\x18\b \x01(\tR\tgitCommit\x12\x16\n" +
	"\x06branch\x18\t \x01(\tR\x06branch\x12\x1c\n" +
	"\tbuildDate\x18\n" +
	" \x01(\tR\tbuildDate\x12\x1c\n" +
	"\tbuildUser\x18\v \x01(\tR\tbuildUser\x12(\n" +
	"\x0festimatedHeight\x18\f \x01(\x04R\x0festimatedHeight\x12 \n" +
	"\vzcashdBuild\x18\r \x01(\tR\vzcashdBuild\x12*\n" +
	"\x10zcashdSubversion\x18\x0e \x01(\tR\x10zcashdSubversion\"\xa6\x02\n" +
	"\fCompactBlock\x12\"\n" +
	"\fprotoVersion\x18\x01 \x01(\rR\fprotoVersion\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\x12\x1a\n" +
	"\bprevHash\x18\x04 \x01(\fR\bprevHash\x12\x12\n" +
	"\x04time\x18\x05 \x01(\rR\x04time\x12\x16\n" +
	"\x06header\x18\x06 \x01(\fR\x06header\x122\n" +
	"\x03vtx\x18\a \x03(\v2 .cash.z.wallet.sdk.rpc.CompactTxR\x03vtx\x12J\n" +
	"\rchainMetadata\x18\b \x01(\v2$.cash.z.wallet.sdk.rpc.ChainMetadataR\rchainMetadata\"\x8b\x01\n" +
	"\rChainMetadata\x12<\n" +
	"\x19saplingCommitmentTreeSize\x18\x01 \x01(\rR\x19saplingCommitmentTreeSize\x12<\n" +
	"\x19orchardCommitmentTreeSize\x18\x02 \x01(\rR\x19orchardCommitmentTreeSize\"\x99\x02\n" +
	"\tCompactTx\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\rR\x03fee\x12B\n" +
	"\x06spends\x18\x04 \x03(\v2*.cash.z.wallet.sdk.rpc.CompactSaplingSpendR\x06spends\x12E\n" +
	"\aoutputs\x18\x05 \x03(\v2+.cash.z.wallet.sdk.rpc.CompactSaplingOutputR\aoutputs\x12E\n" +
	"\aactions\x18\x06 \x03(\v2+.cash.z.wallet.sdk.rpc.CompactOrchardActionR\aactions\"%\n" +
	"\x13CompactSaplingSpend\x12\x0e\n" +
	"\x02nf\x18\x01 \x01(\fR\x02nf\"l\n" +
	"\x14CompactSaplingOutput\x12\x10\n" +
	"\x03cmu\x18\x01 \x01(\fR\x03cmu\x12\"\n" +
	"\fephemeralKey\x18\x02 \x01(\fR\fephemeralKey\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\"\x8a\x01\n" +
	"\x14CompactOrchardAction\x12\x1c\n" +
	"\tnullifier\x18\x01 \x01(\fR\tnullifier\x12\x10\n" +
	"\x03cmx\x18\x02 \x01(\fR\x03cmx\x12\"\n" +
	"\fephemeralKey\x18\x03 \x01(\fR\fephemeralKey\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\"j\n" +
	"\bTxFilter\x124\n" +
	"\x05block\x18\x01 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x05block\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"<\n" +
	"\x0eRawTransaction\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\"\xa9\x01\n" +
	"\tTreeState\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04time\x18\x04 \x01(\rR\x04time\x12 \n" +
	"\vsaplingTree\x18\x05 \x01(\tR\vsaplingTree\x12 \n" +
	"\vorchardTree\x18\x06 \x01(\tR\vorchardTree\"P\n" +
	"\fSendResponse\x12\x1c\n" +
	"\terrorCode\x18\x01 \x01(\x05R\terrorCode\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage2\xfe\x04\n" +
	"\x11CompactTxStreamer\x12T\n" +
	"\x0eGetLatestBlock\x12 .cash.z.wallet.sdk.rpc.ChainSpec\x1a\x1e.cash.z.wallet.sdk.rpc.BlockID\"\x00\x12Q\n" +
	"\bGetBlock\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x00\x12[\n" +
	"\rGetBlockRange\x12!.cash.z.wallet.sdk.rpc.BlockRange\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x000\x01\x12R\n" +
	"\rGetLightdInfo\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a!.cash.z.wallet.sdk.rpc.LightdInfo\"\x00\x12Z\n" +
	"\x0eGetTransaction\x12\x1f.cash.z.wallet.sdk.rpc.TxFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x00\x12R\n" +
	"\fGetTreeState\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a .cash.z.wallet.sdk.rpc.TreeState\"\x00\x12_\n" +
	"\x0fSendTransaction\x12%.cash.z.wallet.sdk.rpc.RawTransaction\x1a#.cash.z.wallet.sdk.rpc.SendResponse\"\x00BAZ?github.com/vultisig/frosty-lib/client/frozt/internal/lightwalletdb\x06proto3"

var (
	file_internal_lightwalletd_compact_formats_proto_rawDescOnce sync.Once
	file_internal_lightwalletd_compact_formats_proto_rawDescData []byte
)

func file_internal_lightwalletd_compact_formats_proto_rawDescGZIP() []byte {
	file_internal_lightwalletd_compact_formats_proto_rawDescOnce.Do(func() {
		file_internal_lightwalletd_compact_formats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_lightwalletd_compact_formats_proto_rawDesc), len(file_internal_lightwalletd_compact_formats_proto_rawDesc)))
	})
	return file_internal_lightwalletd_compact_formats_proto_rawDescData
}

var file_internal_lightwalletd_compact_formats_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_lightwalletd_compact_formats_proto_goTypes = []any{
	(*BlockID)(nil),              // 0: cash.z.wallet.sdk.rpc.BlockID
	(*BlockRange)(nil),           // 1: cash.z.wallet.sdk.rpc.BlockRange
	(*ChainSpec)(nil),            // 2: cash.z.wallet.sdk.rpc.ChainSpec
	(*Empty)(nil),                // 3: cash.z.wallet.sdk.rpc.Empty
	(*LightdInfo)(nil),           // 4: cash.z.wallet.sdk.rpc.LightdInfo
	(*CompactBlock)(nil),         // 5: cash.z.wallet.sdk.rpc.CompactBlock
	(*ChainMetadata)(nil),        // 6: cash.z.wallet.sdk.rpc.ChainMetadata
	(*CompactTx)(nil),            // 7: cash.z.wallet.sdk.rpc.CompactTx
	(*CompactSaplingSpend)(nil),  // 8: cash.z.wallet.sdk.rpc.CompactSaplingSpend
	(*CompactSaplingOutput)(nil), // 9: cash.z.wallet.sdk.rpc.CompactSaplingOutput
	(*CompactOrchardAction)(nil), // 10: cash.z.wallet.sdk.rpc.CompactOrchardAction
	(*TxFilter)(nil),             // 11: cash.z.wallet.sdk.rpc.TxFilter
	(*RawTransaction)(nil),       // 12: cash.z.wallet.sdk.rpc.RawTransaction
	(*TreeState)(nil),            // 13: cash.z.wallet.sdk.rpc.TreeState
	(*SendResponse)(nil),         // 14: cash.z.wallet.sdk.rpc.SendResponse
}
var file_internal_lightwalletd_compact_formats_proto_depIdxs = []int32{
	0,  // 0: cash.z.wallet.sdk.rpc.BlockRange.start:type_name -> cash.z.wallet.sdk.rpc.BlockID
	0,  // 1: cash.z.wallet.sdk.rpc.BlockRange.end:type_name -> cash.z.wallet.sdk.rpc.BlockID
	7,  // 2: cash.z.wallet.sdk.rpc.CompactBlock.vtx:type_name -> cash.z.wallet.sdk.rpc.CompactTx
	6,  // 3: cash.z.wallet.sdk.rpc.CompactBlock.chainMetadata:type_name -> cash.z.wallet.sdk.rpc.ChainMetadata
	8,  // 4: cash.z.wallet.sdk.rpc.CompactTx.spends:type_name -> cash.z.wallet.sdk.rpc.CompactSaplingSpend
	9,  // 5: cash.z.wallet.sdk.rpc.CompactTx.outputs:type_name -> cash.z.wallet.sdk.rpc.CompactSaplingOutput
	10, // 6: cash.z.wallet.sdk.rpc.CompactTx.actions:type_name -> cash.z.wallet.sdk.rpc.CompactOrchardAction
	0,  // 7: cash.z.wallet.sdk.rpc.TxFilter.block:type_name -> cash.z.wallet.sdk.rpc.BlockID
	2,  // 8: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestBlock:input_type -> cash.z.wallet.sdk.rpc.ChainSpec
	0,  // 9: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlock:input_type -> cash.z.wallet.sdk.rpc.BlockID
	1,  // 10: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRange:input_type -> cash.z.wallet.sdk.rpc.BlockRange
	3,  // 11: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLightdInfo:input_type -> cash.z.wallet.sdk.rpc.Empty
	11, // 12: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTransaction:input_type -> cash.z.wallet.sdk.rpc.TxFilter
	0,  // 13: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTreeState:input_type -> cash.z.wallet.sdk.rpc.BlockID
	12, // 14: cash.z.wallet.sdk.rpc.CompactTxStreamer.SendTransaction:input_type -> cash.z.wallet.sdk.rpc.RawTransaction
	0,  // 15: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestBlock:output_type -> cash.z.wallet.sdk.rpc.BlockID
	5,  // 16: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlock:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	5,  // 17: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRange:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	4,  // 18: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLightdInfo:output_type -> cash.z.wallet.sdk.rpc.LightdInfo
	12, // 19: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTransaction:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	13, // 20: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTreeState:output_type -> cash.z.wallet.sdk.rpc.TreeState
	14, // 21: cash.z.wallet.sdk.rpc.CompactTxStreamer.SendTransaction:output_type -> cash.z.wallet.sdk.rpc.SendResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_lightwalletd_compact_formats_proto_init() }
func file_internal_lightwalletd_compact_formats_proto_init() {
	if File_internal_lightwalletd_compact_formats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_lightwalletd_compact_formats_proto_rawDesc), len(file_internal_lightwalletd_compact_formats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_lightwalletd_compact_formats_proto_goTypes,
		DependencyIndexes: file_internal_lightwalletd_compact_formats_proto_depIdxs,
		MessageInfos:      file_internal_lightwalletd_compact_formats_proto_msgTypes,
	}.Build()
	File_internal_lightwalletd_compact_formats_proto = out.File
	file_internal_lightwalletd_compact_formats_proto_goTypes = nil
	file_internal_lightwalletd_compact_formats_proto_depIdxs = nil
}
