[package]
name = "frobt-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "frobtlib"
crate-type = ["cdylib", "rlib"]

[dependencies]
frost-ffi = { path = "../frost-ffi" }
frost-ceremony = { path = "../frost-ceremony" }
frost-session = { path = "../frost-session" }
frost-core = { version = "2", features = ["internals"] }
frost-secp256k1 = "=2.2.0"
k256 = { version = "0.13", features = ["arithmetic"] }
bitcoin = "0.32"
rand = "0.8"
lazy_static = "1.4"
hex = "0.4"
zeroize = { version = "1", features = ["derive"] }
sha2 = "0.10"
hmac = "0.12"

[dev-dependencies]
frost-secp256k1-tr = "=2.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
